# app/core/database/error_codes.py
from enum import StrEnum


class ErrorCode(StrEnum):
    HOME_PERMISSION_DENIED = "HOME_PERMISSION_DENIED"
    ADMIN_ONLY = "ADMIN_ONLY"

    HOME_NOT_FOUND = "HOME_NOT_FOUND"
    HOME_ALREADY_EXISTS = "HOME_ALREADY_EXISTS"
    USER_NOT_FOUND = "USER_NOT_FOUND"

    ALREADY_MEMBER = "ALREADY_MEMBER"
    INVENTORY_ITEM_NAME_CONFLICT = "INVENTORY_ITEM_NAME_CONFLICT"

    OWNER_ASSIGNMENT_NOT_ALLOWED = "OWNER_ASSIGNMENT_NOT_ALLOWED"
    HOME_USER_ALREADY_MEMBER = "HOME_USER_ALREADY_MEMBER"
    TARGET_USER_NOT_FOUND = "TARGET_USER_NOT_FOUND"
    AUTH_REQUIRED = "AUTH_REQUIRED"
    INVENTORY_ACCESS_DENIED = "INVENTORY_ACCESS_DENIED"
