"""

Revision ID: 1d45a9f7e7ad
Revises: 3084df5c4324
Create Date: 2026-02-03 01:26:36.820281

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1d45a9f7e7ad"
down_revision: Union[str, Sequence[str], None] = "3084df5c4324"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "in_app_notifications",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("home_id", sa.UUID(), nullable=False),
        sa.Column("subject", sa.String(length=200), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["event_id"], ["notification_events.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["home_id"], ["homes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "event_id", "user_id", name="uq_notification_inbox_event_user"
        ),
    )
    op.create_index(
        op.f("ix_in_app_notifications_created_at"),
        "in_app_notifications",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_in_app_notifications_event_id"),
        "in_app_notifications",
        ["event_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_in_app_notifications_home_id"),
        "in_app_notifications",
        ["home_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_in_app_notifications_read_at"),
        "in_app_notifications",
        ["read_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_in_app_notifications_updated_at"),
        "in_app_notifications",
        ["updated_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_in_app_notifications_user_id"),
        "in_app_notifications",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        "ix_notification_inbox_user_read",
        "in_app_notifications",
        ["user_id", "read_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_notification_inbox_user_read", table_name="in_app_notifications")
    op.drop_index(
        op.f("ix_in_app_notifications_user_id"), table_name="in_app_notifications"
    )
    op.drop_index(
        op.f("ix_in_app_notifications_updated_at"), table_name="in_app_notifications"
    )
    op.drop_index(
        op.f("ix_in_app_notifications_read_at"), table_name="in_app_notifications"
    )
    op.drop_index(
        op.f("ix_in_app_notifications_home_id"), table_name="in_app_notifications"
    )
    op.drop_index(
        op.f("ix_in_app_notifications_event_id"), table_name="in_app_notifications"
    )
    op.drop_index(
        op.f("ix_in_app_notifications_created_at"), table_name="in_app_notifications"
    )
    op.drop_table("in_app_notifications")
    # ### end Alembic commands ###
