"""

Revision ID: 62330e69e2d9
Revises: 5db31a5dba5c
Create Date: 2026-09-18 13:20:06.868369

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "62330e69e2d9"
down_revision: Union[str, Sequence[str], None] = "5db31a5dba5c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
