"""initial_schema

Revision ID: 7b4376594b22
Revises: 
Create Date: 2026-01-27 13:04:38.696237

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7b4376594b22"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "homes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_homes_created_at"), "homes", ["created_at"], unique=False)
    op.create_index(op.f("ix_homes_updated_at"), "homes", ["updated_at"], unique=False)
    op.create_table(
        "notification_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source", sa.String(length=80), nullable=False),
        sa.Column("event_type", sa.String(length=120), nullable=False),
        sa.Column("subject", sa.String(length=200), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "recipients",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_notification_events_created_at"),
        "notification_events",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_events_updated_at"),
        "notification_events",
        ["updated_at"],
        unique=False,
    )
    op.create_table(
        "notification_outbox",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("topic", sa.String(length=200), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("headers", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("next_retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id"),
    )
    op.create_index(
        op.f("ix_notification_outbox_created_at"),
        "notification_outbox",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_outbox_updated_at"),
        "notification_outbox",
        ["updated_at"],
        unique=False,
    )
    op.create_index(
        "ix_outbox_status_next_retry",
        "notification_outbox",
        ["status", "next_retry_at"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index(op.f("ix_users_created_at"), "users", ["created_at"], unique=False)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_updated_at"), "users", ["updated_at"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "home_users",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("home_id", sa.Uuid(), nullable=False),
        sa.Column(
            "user_type",
            sa.Enum("OWNER", "RESIDENCE", "GUEST", name="user_type_enum"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["home_id"], ["homes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "home_id", name="pk_user_home"),
    )
    op.create_index(
        op.f("ix_home_users_created_at"), "home_users", ["created_at"], unique=False
    )
    op.create_index("ix_home_users_home_id", "home_users", ["home_id"], unique=False)
    op.create_index(
        op.f("ix_home_users_updated_at"), "home_users", ["updated_at"], unique=False
    )
    op.create_index("ix_home_users_user_id", "home_users", ["user_id"], unique=False)
    op.create_table(
        "inventory_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("home_id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "kitchen",
                "bathroom",
                "cleaning",
                "other",
                name="inventory_category_enum",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit", sa.String(length=30), nullable=False),
        sa.Column("expiry_date", sa.Date(), nullable=True),
        sa.Column("notes", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["home_id"], ["homes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("home_id", "name", name="uq_inventory_home_name"),
    )
    op.create_index(
        "ix_inventory_home_category",
        "inventory_items",
        ["home_id", "category"],
        unique=False,
    )
    op.create_index(
        "ix_inventory_home_created_at",
        "inventory_items",
        ["home_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_inventory_home_expiry",
        "inventory_items",
        ["home_id", "expiry_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_items_created_at"),
        "inventory_items",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_items_updated_at"),
        "inventory_items",
        ["updated_at"],
        unique=False,
    )
    op.create_table(
        "notification_deliveries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column(
            "recipient_type",
            sa.Enum(
                "email",
                "phone",
                "slack_channel",
                "in_app_user",
                "log",
                name="notification_recipient_type_enum",
            ),
            nullable=False,
        ),
        sa.Column("recipient", sa.String(length=255), nullable=False),
        sa.Column(
            "channel",
            sa.Enum("email", "sms", "push", "log", name="notification_channel_enum"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "sending",
                "sent",
                "failed",
                "dlq",
                name="notification_delivery_status_enum",
            ),
            nullable=False,
        ),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("next_retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("locked_by", sa.String(length=120), nullable=True),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lock_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["event_id"], ["notification_events.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "event_id",
            "channel",
            "recipient_type",
            "recipient",
            name="uq_delivery_per_target",
        ),
    )
    op.create_index(
        op.f("ix_notification_deliveries_channel"),
        "notification_deliveries",
        ["channel"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_deliveries_created_at"),
        "notification_deliveries",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_deliveries_event_id"),
        "notification_deliveries",
        ["event_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_notification_deliveries_lock_expires_at"),
        "notification_deliveries",
        ["lock_expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_deliveries_locked_at"),
        "notification_deliveries",
        ["locked_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_deliveries_locked_by"),
        "notification_deliveries",
        ["locked_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_deliveries_next_retry_at"),
        "notification_deliveries",
        ["next_retry_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_deliveries_status"),
        "notification_deliveries",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_deliveries_updated_at"),
        "notification_deliveries",
        ["updated_at"],
        unique=False,
    )
    op.create_table(
        "inventory_expiry_alerts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("inventory_item_id", sa.UUID(), nullable=False),
        sa.Column(
            "alert_type",
            sa.Enum(
                "expired",
                "expiring_soon",
                name="inventory_alert_type_enum",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("alert_date", sa.Date(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("publish_attempts", sa.Integer(), nullable=False),
        sa.Column("last_publish_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["inventory_item_id"], ["inventory_items.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "inventory_item_id",
            "alert_type",
            "alert_date",
            name="uq_item_alert_once_per_day",
        ),
    )
    op.create_index(
        op.f("ix_inventory_expiry_alerts_created_at"),
        "inventory_expiry_alerts",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_expiry_alerts_inventory_item_id"),
        "inventory_expiry_alerts",
        ["inventory_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_expiry_alerts_published_at"),
        "inventory_expiry_alerts",
        ["published_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_expiry_alerts_updated_at"),
        "inventory_expiry_alerts",
        ["updated_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_inventory_expiry_alerts_updated_at"),
        table_name="inventory_expiry_alerts",
    )
    op.drop_index(
        op.f("ix_inventory_expiry_alerts_published_at"),
        table_name="inventory_expiry_alerts",
    )
    op.drop_index(
        op.f("ix_inventory_expiry_alerts_inventory_item_id"),
        table_name="inventory_expiry_alerts",
    )
    op.drop_index(
        op.f("ix_inventory_expiry_alerts_created_at"),
        table_name="inventory_expiry_alerts",
    )
    op.drop_table("inventory_expiry_alerts")
    op.drop_index(
        op.f("ix_notification_deliveries_updated_at"),
        table_name="notification_deliveries",
    )
    op.drop_index(
        op.f("ix_notification_deliveries_status"), table_name="notification_deliveries"
    )
    op.drop_index(
        op.f("ix_notification_deliveries_next_retry_at"),
        table_name="notification_deliveries",
    )
    op.drop_index(
        op.f("ix_notification_deliveries_locked_by"),
        table_name="notification_deliveries",
    )
    op.drop_index(
        op.f("ix_notification_deliveries_locked_at"),
        table_name="notification_deliveries",
    )
    op.drop_index(
        op.f("ix_notification_deliveries_lock_expires_at"),
        table_name="notification_deliveries",
    )
    op.drop_index(
        op.f("ix_notification_deliveries_event_id"),
        table_name="notification_deliveries",
    )
    op.drop_index(
        op.f("ix_notification_deliveries_created_at"),
        table_name="notification_deliveries",
    )
    op.drop_index(
        op.f("ix_notification_deliveries_channel"), table_name="notification_deliveries"
    )
    op.drop_table("notification_deliveries")
    op.drop_index(op.f("ix_inventory_items_updated_at"), table_name="inventory_items")
    op.drop_index(op.f("ix_inventory_items_created_at"), table_name="inventory_items")
    op.drop_index("ix_inventory_home_expiry", table_name="inventory_items")
    op.drop_index("ix_inventory_home_created_at", table_name="inventory_items")
    op.drop_index("ix_inventory_home_category", table_name="inventory_items")
    op.drop_table("inventory_items")
    op.drop_index("ix_home_users_user_id", table_name="home_users")
    op.drop_index(op.f("ix_home_users_updated_at"), table_name="home_users")
    op.drop_index("ix_home_users_home_id", table_name="home_users")
    op.drop_index(op.f("ix_home_users_created_at"), table_name="home_users")
    op.drop_table("home_users")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_updated_at"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_created_at"), table_name="users")
    op.drop_table("users")
    op.drop_index("ix_outbox_status_next_retry", table_name="notification_outbox")
    op.drop_index(
        op.f("ix_notification_outbox_updated_at"), table_name="notification_outbox"
    )
    op.drop_index(
        op.f("ix_notification_outbox_created_at"), table_name="notification_outbox"
    )
    op.drop_table("notification_outbox")
    op.drop_index(
        op.f("ix_notification_events_updated_at"), table_name="notification_events"
    )
    op.drop_index(
        op.f("ix_notification_events_created_at"), table_name="notification_events"
    )
    op.drop_table("notification_events")
    op.drop_index(op.f("ix_homes_updated_at"), table_name="homes")
    op.drop_index(op.f("ix_homes_created_at"), table_name="homes")
    op.drop_table("homes")
    # ### end Alembic commands ###
