"""Remove name from inventory_items; require product_id (issue #48).

Precondition: every inventory_items row must already have a product_id by
the time this runs -- the c47e9f21a6b8 backfill (issue #44) is responsible
for that. This migration only flips the contract (NOT NULL + drop the old
column/constraint); it does not itself assign any product_id values. If a
row somehow still has product_id IS NULL, we raise a clear error instead of
letting the ALTER COLUMN ... NOT NULL fail with an opaque constraint error.

Revision ID: cd976705f515
Revises: c47e9f21a6b8
Create Date: 2026-09-18 21:27:13.848837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd976705f515'
down_revision: Union[str, Sequence[str], None] = 'c47e9f21a6b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()

    missing = conn.execute(
        sa.text(
            "SELECT count(*) FROM inventory_items WHERE product_id IS NULL"
        )
    ).scalar_one()
    if missing:
        raise RuntimeError(
            f"{missing} inventory_items row(s) still have product_id IS NULL; "
            "run the c47e9f21a6b8 backfill (issue #44) before this migration."
        )

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inventory_items', 'product_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('uq_inventory_home_name'), 'inventory_items', type_='unique')
    # NOTE: ix_inventory_items_product_id already exists (created by
    # 4304258471a2 and never dropped since) -- autogenerate mis-detected it
    # as missing; adjusted out to avoid a duplicate-relation error.
    op.drop_column('inventory_items', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # Not supported: the original free-text `name` values are gone for good
    # once dropped, so there's no data to restore them from. Re-adding an
    # empty/NOT-NULL `name` column would either fail immediately against
    # existing rows or silently fabricate placeholder data -- neither is a
    # real downgrade.
    raise RuntimeError(
        "Downgrade not supported: inventory_items.name data is unrecoverable "
        "once this migration has run."
    )
