"""

Revision ID: 5db31a5dba5c
Revises: 8a1f2c9d4e6b
Create Date: 2026-09-18 13:18:39.911233

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5db31a5dba5c"
down_revision: Union[str, Sequence[str], None] = "8a1f2c9d4e6b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_notification_inbox_event_user"), "in_app_notifications", type_="unique"
    )
    op.drop_index(op.f("ix_inventory_items_product_id"), table_name="inventory_items")
    op.alter_column(
        "notification_deliveries",
        "context",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.create_index(
        op.f("ix_notification_deliveries_event_id"),
        "notification_deliveries",
        ["event_id"],
        unique=False,
    )
    op.drop_index(
        op.f("ix_notification_outbox_status_next_retry"),
        table_name="notification_outbox",
    )
    op.drop_constraint(
        op.f("notification_outbox_event_id_key"), "notification_outbox", type_="unique"
    )
    op.create_index(
        op.f("ix_notification_outbox_next_retry_at"),
        "notification_outbox",
        ["next_retry_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_notification_outbox_next_retry_at"), table_name="notification_outbox"
    )
    op.create_unique_constraint(
        op.f("notification_outbox_event_id_key"),
        "notification_outbox",
        ["event_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("ix_notification_outbox_status_next_retry"),
        "notification_outbox",
        ["status", "next_retry_at"],
        unique=False,
    )
    op.drop_index(
        op.f("ix_notification_deliveries_event_id"),
        table_name="notification_deliveries",
    )
    op.alter_column(
        "notification_deliveries",
        "context",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.create_index(
        op.f("ix_inventory_items_product_id"),
        "inventory_items",
        ["product_id"],
        unique=False,
    )
    op.create_unique_constraint(
        op.f("uq_notification_inbox_event_user"),
        "in_app_notifications",
        ["event_id", "user_id"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
